# -*- mode: python -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['D:\\Python\\19_Scrapy\\WOS_Crawl_UI_Test\\post_test'],
             binaries=[],
             datas=[],
             hiddenimports=['scrapy.spiderloader',
                'scrapy.statscollectors',
                'scrapy.logformatter',
                'scrapy.dupefilters',
                'scrapy.squeues',
                'scrapy.extensions.spiderstate',
                'scrapy.extensions.corestats',
                'scrapy.extensions.telnet',
                'scrapy.extensions.logstats',
                'scrapy.extensions.memusage',
                'scrapy.extensions.memdebug',
                'scrapy.extensions.feedexport',
                'scrapy.extensions.closespider',
                'scrapy.extensions.debug',
                'scrapy.extensions.httpcache',
                'scrapy.extensions.statsmailer',
                'scrapy.extensions.throttle',
                'scrapy.core.scheduler',
                'scrapy.core.engine',
                'scrapy.core.scraper',
                'scrapy.core.spidermw',
                'scrapy.core.downloader',
                'scrapy.downloadermiddlewares.stats',
                'scrapy.downloadermiddlewares.httpcache',
                'scrapy.downloadermiddlewares.cookies',
                'scrapy.downloadermiddlewares.useragent',
                'scrapy.downloadermiddlewares.httpproxy',
                'scrapy.downloadermiddlewares.ajaxcrawl',
                'scrapy.downloadermiddlewares.chunked',
                'scrapy.downloadermiddlewares.decompression',
                'scrapy.downloadermiddlewares.defaultheaders',
                'scrapy.downloadermiddlewares.downloadtimeout',
                'scrapy.downloadermiddlewares.httpauth',
                'scrapy.downloadermiddlewares.httpcompression',
                'scrapy.downloadermiddlewares.redirect',
                'scrapy.downloadermiddlewares.retry',
                'scrapy.downloadermiddlewares.robotstxt',
                'scrapy.spidermiddlewares.depth',
                'scrapy.spidermiddlewares.httperror',
                'scrapy.spidermiddlewares.offsite',
                'scrapy.spidermiddlewares.referer',
                'scrapy.spidermiddlewares.urllength',
                'scrapy.pipelines',
                'scrapy.core.downloader.handlers.http',
                'scrapy.core.downloader.contextfactory',
                'sqlite3',
                'fake_useragent',
                'bibtexparser'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )
